--DROP DATABASE
DROP DATABASE BancoSQL;

-- Criaçao do Banco de Dados
CREATE DATABASE BancoSQL;

-- Definir qual banco de dados vamos utilizar
USE BancoSQL;
GO

-- TABELA PRODUTOS
DROP TABLE DBO.PRODUTO;
GO

CREATE TABLE PRODUTO(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(50),
	DESCRICAO VARCHAR(255),
	TIPO CHAR(1),
	VALOR DECIMAL(5,2),
	CONSTRAINT PK_PRODUTO PRIMARY KEY(ID)
);
GO

-- TABELA FORMA DE PAGAMENTO
DROP TABLE FORMA_PAGAMENTO;
GO

CREATE TABLE FORMA_PAGAMENTO(
	ID INT IDENTITY(1,1) NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	CONSTRAINT PK_FORMA_PAGAMENTO PRIMARY KEY(ID)
);
GO

-- TABELA FUNCIONARIO
DROP TABLE FUNCIONARIO;
GO

CREATE TABLE FUNCIONARIO(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	SALARIO DECIMAL(6,2) NOT NULL,
	-- COD ENDERECO
	TIPO CHAR(1) NULL,
	N_CONSELHO INT NULL,
	ESPECIALIDADE VARCHAR(20) NULL,
	COMISSAO DECIMAL(4,2),
	CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(ID)
);
GO

-- TABELA CLIENTE
DROP TABLE CLIENTE;
GO

CREATE TABLE CLIENTE(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	-- COD_ENDERECO
	-- TELEFONE
	EMAIL VARCHAR(50) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(ID)
);
GO

-- TABELA PRONTUARIO
DROP TABLE PRONTUARIO;
GO

CREATE TABLE PRONTUARIO (
	ID INT IDENTITY(1,1) NOT NULL,
	DESCRICAO VARCHAR(255),
	TEMPERATURA DECIMAL(3,1),
	PESO DECIMAL(3,1),
	CONSTRAINT PK_PRONTUARIO PRIMARY KEY(ID)
);
GO

-- TABELA PET
DROP TABLE PET;
GO

CREATE TABLE PET(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(50),
	ESPECIE VARCHAR(50),
	PORTE VARCHAR(50),
	DT_NASC DATE,
	ID_PRONTUARIO INT NULL,
	CONSTRAINT PK_PET PRIMARY KEY(ID),
	CONSTRAINT FK_PET_PRONTUARIO FOREIGN KEY(ID_PRONTUARIO)
	REFERENCES DBO.PRONTUARIO (ID)
);
GO

-- TABELA CLIENTE-PET
DROP TABLE CLIENTE_PET;
GO

CREATE TABLE CLIENTE_PET(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_PET INT NOT NULL,
	CONSTRAINT PK_CLIENTE_PET PRIMARY KEY(ID),
	CONSTRAINT FK_CLIENTE_PET_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES DBO.CLIENTE (ID),
	CONSTRAINT FK_CLIENTE_PET_PET FOREIGN KEY (ID_PET)
	REFERENCES DBO.PET (ID)
);
GO

-- TABELA VENDA
DROP TABLE VENDA;
GO

CREATE TABLE VENDA(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_FORMA_PAGAMENTO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_FUNCIONARIO INT NOT NULL,
	CONSTRAINT PK_VENDA PRIMARY KEY(ID),
	CONSTRAINT FK_VENDA_FORMA_PAGAMENTO FOREIGN KEY(ID_FORMA_PAGAMENTO)
	REFERENCES DBO.FORMA_PAGAMENTO (ID),
	CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES DBO.CLIENTE (ID),
	CONSTRAINT FK_vENDA_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
	REFERENCES DBO.FUNCIONARIO (ID)
);
GO

-- TABELA PRODUTO_VENDA
DROP TABLE PRODUTO_VENDA;
GO

CREATE TABLE PRODUTO_VENDA(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_VENDA INT NOT NULL,
	CONSTRAINT PK_PRODUTO_VENDA PRIMARY KEY(ID, ID_PRODUTO, ID_VENDA),
	CONSTRAINT FK_PRODUTO_VENDA_PRODUTO FOREIGN KEY (ID_PRODUTO)
	REFERENCES DBO.PRODUTO (ID),
	CONSTRAINT FK_PRODUTO_VENDA_VENDA FOREIGN KEY (ID_VENDA)
	REFERENCES DBO.VENDA (ID)
);
GO

USE BancoSQL;
GO

-- TABELA CLIENTE_PET

ALTER TABLE CLIENTE_PET
DROP CONSTRAINT FK_CLIENTE_PET_CLIENTE;

ALTER TABLE CLIENTE_PET
drop CONSTRAINT FK_CLIENTE_PET_PET;

ALTER TABLE CLIENTE_PET
ADD CONSTRAINT FK_CLIENTE_PET_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES DBO.CLIENTE (ID)
	ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_CLIENTE_PET_PET FOREIGN KEY (ID_PET)
	REFERENCES DBO.PET (ID)
    ON DELETE CASCADE ON UPDATE NO ACTION;


-- TABELA PET
ALTER TABLE PET
drop CONSTRAINT FK_PET_PRONTUARIO;

ALTER TABLE PET
ADD CONSTRAINT FK_PET_PRONTUARIO FOREIGN KEY(ID_PRONTUARIO)
	REFERENCES DBO.PRONTUARIO (ID)
	ON DELETE CASCADE ON UPDATE NO ACTION;


-- TABELA VENDA

ALTER TABLE VENDA
drop CONSTRAINT FK_VENDA_CLIENTE;

ALTER TABLE VENDA
drop CONSTRAINT FK_VENDA_FORMA_PAGAMENTO;

ALTER TABLE VENDA
drop CONSTRAINT FK_VENDA_FUNCIONARIO;

ALTER TABLE VENDA
ADD CONSTRAINT FK_VENDA_FORMA_PAGAMENTO FOREIGN KEY(ID_FORMA_PAGAMENTO)
	REFERENCES DBO.FORMA_PAGAMENTO (ID)
	ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES DBO.CLIENTE (ID)
	ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_vENDA_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
	REFERENCES DBO.FUNCIONARIO (ID)
	ON DELETE CASCADE ON UPDATE NO ACTION;


-- TABELA PRODUTO_VENDA

ALTER TABLE PRODUTO_VENDA
drop CONSTRAINT FK_PRODUTO_VENDA_VENDA;

ALTER TABLE PRODUTO_VENDA
drop CONSTRAINT FK_PRODUTO_VENDA_PRODUTO;

ALTER TABLE PRODUTO_VENDA
ADD CONSTRAINT FK_PRODUTO_VENDA_PRODUTO FOREIGN KEY (ID_PRODUTO)
	REFERENCES DBO.PRODUTO (ID)
	ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_PRODUTO_VENDA_VENDA FOREIGN KEY (ID_VENDA)
	REFERENCES DBO.VENDA (ID)
	ON DELETE CASCADE ON UPDATE NO ACTION;


-- TABELA FUNCIONARIOS
ALTER TABLE DBO.FUNCIONARIO
ALTER COLUMN CPF VARCHAR(14);

   
USE BancoSQL;
GO

-- INSERT FORMAS DE PAGAMENTO

DELETE FROM DBO.FORMA_PAGAMENTO;
DBCC CHECKIDENT ('FORMA_PAGAMENTO', RESEED, 0);
GO

INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Dinheiro');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Cart�o de D�bito');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Cart�o de Cr�dito (Vencimento)');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Cart�o de Cr�dito (Parcelado)');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Carn�');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Pix');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('PicPay');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Google Pay');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Mercado Pago');

-- TABELA PRODUTO

DELETE FROM DBO.PRODUTO;
DBCC CHECKIDENT ('PRODUTO', RESEED, 0);
GO

INSERT INTO DBO.PRODUTO VALUES
('Bola de brinquedo', 'Bola para morder e pegar para cachorros', 'P', 10.00);
INSERT INTO DBO.PRODUTO VALUES
('Shampo Pet Love', 'Para um banho cheiroso', 'P', 13.00);
INSERT INTO DBO.PRODUTO VALUES
('Banho e Tosa', 'Servi�o de est�tica', 'S', 60.00);
INSERT INTO DBO.PRODUTO VALUES
('Coleira', 'Seguran�a para seu pet', 'P', 66.90);
INSERT INTO DBO.PRODUTO VALUES
('Consulta Veterin�ria', 'Consulta especializada', 'S', 299.90);
INSERT INTO DBO.PRODUTO VALUES
('Ra��o Atacama 16kg', 'Ra��o boa pra cachorro', 'P', 230.99);
INSERT INTO DBO.PRODUTO VALUES
('Bola de brinquedo', 'Bola para morder e pegar para cachorros', 'P', 10.00);
INSERT INTO DBO.PRODUTO VALUES
('Catnip 10g', 'Erva de gato desidratada', 'P', 25.98);
INSERT INTO DBO.PRODUTO VALUES
('Pedras de fire', 'Ra��o crocante e flamejante', 'P', 15.50);
INSERT INTO DBO.PRODUTO VALUES
('Remedio pulkill', 'Matar pulga ', 'P', 90.81);
INSERT INTO DBO.PRODUTO VALUES
('Ra��o Wiskas', 'Ra��o para gatos', 'P', 20.87);
INSERT INTO DBO.PRODUTO VALUES
('Correntes de Asgard ', 'Correntes que prederam o lobo Fenrir de Asgard', 'P', 88.90);
INSERT INTO DBO.PRODUTO VALUES
('Sampoo Premium', 'Shampoo da linha premium para pelos sedosos', 'P', 250.87);
INSERT INTO DBO.PRODUTO VALUES
('Ra��es Pilar', 'Comida de cachorro', 'P', 88.90);
INSERT INTO DBO.PRODUTO VALUES
('Mordedor', 'Mordedor para cachorro de grande porte', 'P', 58.90);
INSERT INTO DBO.PRODUTO VALUES
('Ra��o mania', 'Comida de cachorro', 'P', 58.91);
INSERT INTO DBO.PRODUTO VALUES
('Osso Roedor', 'Ossinho de roer para cachorro inquieto', 'P', 58.92);
INSERT INTO DBO.PRODUTO VALUES
('Gaiola roedores', 'Gaiola para pequenos roedores - tamanho medio ', 'P', 58.93);

-- TABELA CLIENTES

DELETE FROM DBO.CLIENTE;
DBCC CHECKIDENT ('CLIENTE', RESEED, 0);
GO

INSERT INTO DBO.CLIENTE VALUES
('Levi de Souza Folly', 'levi.folly@geradornv.com.br'),
('Everton Cormack Siqueira', 'everton.siqueira@geradornv.com.br'),
('Estefani Guimar�es Claudino', 'estefani.claudino@geradornv.com.br'),
('Alessandro Temperini Antunes', 'alessandro.antunes@geradornv.com.br'),
('Islayne Hall Mour�o', 'islayne.mourao@geradornv.com.br'),
('Jonathan Branco Zuniga', 'jonathan.zuniga@geradornv.com.br'),
('Rozangela de Barros Queiroz', 'rozangela.queiroz@geradornv.com.br'),
('Katyene da Concei��o Bravo', 'katyene.bravo@geradornv.com.br'),
('D�bora Matta Valente', 'debora.valente@geradornv.com.br'),
('Hebert Cardoso Filho', 'hebert.filho@geradornv.com.br'),
('Emanoel Pires Lana', 'emanoel.lana@geradornv.com.br'),
('Eliana Branco Gomes', 'eliana.gomes@geradornv.com.br'),
('Lucy da Cunha Carmanin', 'lucy.carmanin@geradornv.com.br'),
('Vilma Sarmento Sarmanto', 'vilma.sarmanto@geradornv.com.br');


-- TABELA FUNCION�RIOS

DELETE FROM DBO.FUNCIONARIO;
DBCC CHECKIDENT ('FUNCIONARIO', RESEED, 0);
GO


INSERT INTO DBO.FUNCIONARIO VALUES
('Rosimere Theodoro Manh�es', '387.867.049-40', 2500.00, 'V', 696432, 'Geral', NULL),
('Jos� Da Silva', '798.783.146-65', 5000.00, 'V', 23456789, 'Dermatologia', NULL),
('Osmar Osvaldo', '111.222.333-04', 2500.00, 'V', 7632198, 'Geral', NULL),
('Hermenegildo Batista', '552.443.644-76', 3500.00, 'V', 6743856, 'Oncologista', NULL),
('Joaquim Da Silva Santos', '121.077.452-85', 9785.00, 'V', 675897, 'Oncologista', NULL),
('Pedro Thomas Monteiro', '567.659.342-35', 3000, 'V', 21423, 'Dermatologia', NULL),
('Jo�o Lima', '777.949.230-34', 1310.17, 'A', NULL, NULL, 7),       
('Jeniffer Batista', '189.684.123-99', 1580.25, 'A', NULL, NULL, 11),
('Aline Omar', '400.289.221-88', 1367.80, 'A', NULL, NULL, 8);

-- TABELA PETS

DELETE FROM PET;
DBCC CHECKIDENT ('PET', RESEED, 0);
GO

INSERT INTO DBO.PET VALUES
('Marley', 'Cachorro', 'M', NULL, NULL),
('Dog�o', 'Cachorro', 'P', NULL, NULL),
('Simba', 'Gato', 'M', NULL, NULL),
('Kira Maria', 'Gato', 'M', NULL, NULL),
('Ligerinho', 'Jabuti', 'P', NULL, NULL),
('To�co', 'Papagaio', 'M', NULL, NULL),
('Judith Pereira', 'Gato', 'M', NULL, NULL),
('Nine', 'Cachorro', 'M', NULL, NULL),
('Teddy', 'Cachorro', 'P', NULL, NULL);


-- INSERINDO VENDAS
DELETE FROM DBO.VENDA;
DBCC CHECKIDENT ('VENDA', RESEED, 0);
GO

INSERT INTO DBO.VENDA VALUES(1, 1, 7);
INSERT INTO DBO.VENDA VALUES(6, 3, 9);
INSERT INTO DBO.VENDA VALUES(6, 13, 8);
INSERT INTO DBO.VENDA VALUES(1, 4, 7);
INSERT INTO DBO.VENDA VALUES(3, 13, 9);
INSERT INTO DBO.VENDA VALUES(6, 8, 7);
INSERT INTO DBO.VENDA VALUES(1, 1, 9);
INSERT INTO DBO.VENDA VALUES(3, 4, 8);
INSERT INTO DBO.VENDA VALUES(1, 13, 7);


-- INSERINDO PRODUTOS VENDIDOS
DELETE FROM DBO.PRODUTO_VENDA;
DBCC CHECKIDENT ('PRODUTO_VENDA', RESEED, 0);
GO

INSERT INTO DBO.PRODUTO_VENDA VALUES
(6, 1),
(5, 1),
(7, 1);

INSERT INTO DBO.PRODUTO_VENDA VALUES
(2, 2),
(5, 2);

INSERT INTO DBO.PRODUTO_VENDA VALUES
(6, 3),
(9, 3),
(4, 3),
(7, 3);

INSERT INTO DBO.PRODUTO_VENDA VALUES
(10, 4);

INSERT INTO DBO.PRODUTO_VENDA VALUES
(12, 5);

INSERT INTO DBO.PRODUTO_VENDA VALUES
(17, 6),
(14, 6);

INSERT INTO DBO.PRODUTO_VENDA VALUES
(7, 7);

INSERT INTO DBO.PRODUTO_VENDA VALUES
(17, 8);

INSERT INTO DBO.PRODUTO_VENDA VALUES
(9, 9);


USE BancoSQL;

-- SELECT SIMPLES PARA VERIFICAR O CONTE�DO
-- DE CADA TABELA

SELECT * FROM PRODUTO;

SELECT * FROM FUNCIONARIO;

SELECT * FROM VENDA;

SELECT * FROM CLIENTE;

SELECT * FROM PET;

-- MOSTRANDO APENAS LINHAS �NICAS

SELECT DISTINCT ESPECIE FROM PET;

SELECT DISTINCT TIPO FROM PRODUTO;

SELECT DISTINCT TIPO FROM FUNCIONARIO;

-- FILTRANDO COM WHERE

SELECT * FROM PRODUTO
WHERE TIPO = 'S'

SELECT * FROM FUNCIONARIO
WHERE TIPO = 'A'

SELECT * FROM PET
WHERE ESPECIE = 'Cachorro'

SELECT DISTINCT PORTE FROM PET
WHERE ESPECIE = 'Cachorro'

-- AGRUPANDO OS RESULTADOS

SELECT ESPECIALIDADE FROM FUNCIONARIO
GROUP BY ESPECIALIDADE, TIPO
HAVING TIPO = 'V'

SELECT TIPO, NOME FROM PRODUTO
GROUP BY TIPO, NOME, VALOR
HAVING VALOR < 30.0

-- ORDER BY

SELECT * FROM PRODUTO
ORDER BY NOME

SELECT * FROM FUNCIONARIO
ORDER BY NOME

SELECT * FROM CLIENTE
ORDER BY NOME

-- Between

SELECT * FROM PRODUTO
WHERE ID BETWEEN 3 AND 10

SELECT * FROM PRODUTO
WHERE VALOR BETWEEN 25.00 AND 60.00

-- COUNT

SELECT TIPO FROM DBO.FUNCIONARIO
GROUP BY TIPO
HAVING COUNT(TIPO) > 1